{
  description = "Claude-OS: Self-evolving AI-native operating system";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs, ... }:
    let
      # Shared modules used by all configurations
      coreModules = [
        ./modules/base
        ./modules/state
        ./modules/shell-agent
        ./modules/master-agent
        ./modules/mcp-servers
        ./modules/memory
        ./modules/awareness
        ./modules/gpu
      ];

      # Helper to build a claude-os NixOS configuration
      mkClaudeOS = { system, extraModules ? [] }:
        nixpkgs.lib.nixosSystem {
          inherit system;
          modules = coreModules ++ [
            ({ ... }: { nixpkgs.config.allowUnfree = true; })
          ] ++ extraModules;
        };

      # VM-specific configuration (shared between dev and prod VMs)
      vmModule = { modulesPath, ... }: {
        imports = [ "${modulesPath}/virtualisation/qemu-vm.nix" ];
        virtualisation = {
          memorySize = 4096;
          cores = 4;
          diskSize = 20480;
          graphics = false;
          forwardPorts = [
            { from = "host"; host.port = 2222; guest.port = 22; }
            { from = "host"; host.port = 11434; guest.port = 11434; } # Ollama API
          ];
        };
      };

    in
    {
      # =============================================
      # NixOS Configurations
      # =============================================

      # Development: aarch64-linux VM (fast builds on arm64 Mac)
      nixosConfigurations.claude-os-dev = mkClaudeOS {
        system = "aarch64-linux";
        extraModules = [ vmModule ];
      };

      # x86_64 VM without NVIDIA (for CI and non-GPU machines)
      nixosConfigurations.claude-os-x86 = mkClaudeOS {
        system = "x86_64-linux";
        extraModules = [ vmModule ];
      };

      # Production: x86_64-linux VM (full NVIDIA/CUDA + Ollama)
      nixosConfigurations.claude-os = mkClaudeOS {
        system = "x86_64-linux";
        extraModules = [
          vmModule
          ({ ... }: { claude-os.nvidia.enable = true; })
        ];
      };

      # Bare-metal install target (x86_64, no VM module)
      nixosConfigurations.claude-os-bare = mkClaudeOS {
        system = "x86_64-linux";
        extraModules = [
          # Bare-metal needs its own hardware-configuration.nix
          # Generated by nixos-generate-config during install
          ({ ... }: {
            claude-os.nvidia.enable = true;
            boot.loader.systemd-boot.enable = true;
            boot.loader.efi.canTouchEfiVariables = true;
            fileSystems."/" = { device = "/dev/disk/by-label/nixos"; fsType = "ext4"; };
            fileSystems."/boot" = { device = "/dev/disk/by-label/boot"; fsType = "vfat"; };
            swapDevices = [ { device = "/dev/disk/by-label/swap"; } ];
          })
        ];
      };

      # ISO installer (x86_64)
      nixosConfigurations.claude-os-iso = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = coreModules ++ [
          ./modules/iso
          ({ ... }: {
            nixpkgs.config.allowUnfree = true;
            claude-os.nvidia.enable = true;
          })
        ];
      };

      # ISO installer (aarch64)
      nixosConfigurations.claude-os-iso-arm = nixpkgs.lib.nixosSystem {
        system = "aarch64-linux";
        modules = coreModules ++ [
          ./modules/iso
          ({ ... }: { nixpkgs.config.allowUnfree = true; })
        ];
      };

      # =============================================
      # Packages
      # =============================================

      # Dev VM (aarch64)
      packages.aarch64-linux.vm = self.nixosConfigurations.claude-os-dev.config.system.build.vm;
      packages.aarch64-linux.default = self.packages.aarch64-linux.vm;
      packages.aarch64-linux.iso = self.nixosConfigurations.claude-os-iso-arm.config.system.build.isoImage;

      # x86_64 VM (without NVIDIA — builds on any machine)
      packages.x86_64-linux.vm = self.nixosConfigurations.claude-os-x86.config.system.build.vm;
      packages.x86_64-linux.default = self.packages.x86_64-linux.vm;
      # x86_64 VM with NVIDIA/CUDA (needs NVIDIA binary cache)
      packages.x86_64-linux.vm-nvidia = self.nixosConfigurations.claude-os.config.system.build.vm;
      packages.x86_64-linux.iso = self.nixosConfigurations.claude-os-iso.config.system.build.isoImage;

      # =============================================
      # Dev Shells
      # =============================================

      devShells.aarch64-darwin.default = let
        pkgs = import nixpkgs { system = "aarch64-darwin"; };
      in pkgs.mkShell {
        packages = with pkgs; [ qemu ];
      };

      devShells.x86_64-darwin.default = let
        pkgs = import nixpkgs { system = "x86_64-darwin"; };
      in pkgs.mkShell {
        packages = with pkgs; [ qemu ];
      };
    };
}
