{ config, pkgs, lib, ... }:

{
  # VM-optimized hardware configuration
  # Filesystem mounts are handled by the virtualisation.qemu-vm module
  # This file covers kernel modules and hardware detection

  # VirtIO support for QEMU/KVM
  boot.kernelModules = [
    "virtio_pci"
    "virtio_net"
    "virtio_blk"
    "virtio_balloon"
    "virtio_console"
  ];

  # QEMU guest agent for host communication
  services.qemuGuest.enable = true;

  # Filesystem support
  boot.supportedFilesystems = [ "ext4" "btrfs" "vfat" ];

  # Note: fileSystems and swapDevices are NOT defined here.
  # The qemu-vm.nix module provides its own root filesystem.
  # For bare-metal installs, a separate hardware-configuration.nix
  # will be generated by nixos-generate-config.
}
